// Generated by CoffeeScript 2.5.1
var userlink, users;

users = [
  {
    "name": "Based and Jedpilled",
    "stats": {
      "spos": 73.5,
      "alle": 70.0,
      "expr": 66.7,
      "pers": 75.0,
      "horn": 8.3,
      "fame": 59.0,
      "shwr": 43.5,
      "sani": 79.3,
      "rela": 73.9,
      "fedp": 60.7,
      "actn": 52.6,
      "purp": 78.9,
      "perc": 73.3,
      "cmdy": 79.7
    }
  },
  {
    "name": "nguyenreich",
    "stats": {
      "spos": 53.4,
      "alle": 31.6,
      "expr": 65.3,
      "pers": 80.9,
      "horn": 60.0,
      "fame": 92.4,
      "shwr": 52.7,
      "sani": 68.1,
      "rela": 77.4,
      "fedp": 13.1,
      "actn": 70.5,
      "purp": 63.7,
      "perc": 81.7,
      "cmdy": 70.4
    }
  },
  {
    "name": "Kaiser",
    "stats": {
      "spos": 70.1,
      "alle": 63.3,
      "expr": 91.7,
      "pers": 44.0,
      "horn": 13.4,
      "fame": 90.9,
      "shwr": 41.0,
      "sani": 44.5,
      "rela": 91.7,
      "fedp": 91.7,
      "actn": 75.6,
      "purp": 34.9,
      "perc": 71.7,
      "cmdy": 83.3
    }
  },
  {
    "name": "Erstanden",
    "stats": {
      "spos": 56.8,
      "alle": 91.7,
      "expr": 34.8,
      "pers": 42.9,
      "horn": 33.3,
      "fame": 27.2,
      "shwr": 30.7,
      "sani": 48.7,
      "rela": 44.1,
      "fedp": 81.0,
      "actn": 40.9,
      "purp": 34.9,
      "perc": 51.8,
      "cmdy": 40.8
    }
  },
  {
    "name": "ItsDanny101",
    "stats": {
      "spos": 45.8,
      "alle": 54.1,
      "expr": 77.8,
      "pers": 79.1,
      "horn": 0.0,
      "fame": 79.3,
      "shwr": 58.4,
      "sani": 54.1,
      "rela": 79.3,
      "fedp": 54.0,
      "actn": 70.1,
      "purp": 8.3,
      "perc": 66.6,
      "cmdy": 75.0
    }
  },
  {
    "name": "KEVIN",
    "stats": {
      "spos": 55.0,
      "alle": 53.3,
      "expr": 94.5,
      "pers": 57.2,
      "horn": 76.7,
      "fame": 83.3,
      "shwr": 39.8,
      "sani": 65.3,
      "rela": 86.9,
      "fedp": 51.2,
      "actn": 64.1,
      "purp": 71.2,
      "perc": 48.4,
      "cmdy": 79.6
    }
  },
  {
    "name": "SteelSmasher",
    "stats": {
      "spos": 70.0,
      "alle": 45.0,
      "expr": 33.3,
      "pers": 64.3,
      "horn": 40.0,
      "fame": 57.5,
      "shwr": 47.4,
      "sani": 70.9,
      "rela": 51.2,
      "fedp": 28.5,
      "actn": 71.8,
      "purp": 51.5,
      "perc": 50.0,
      "cmdy": 57.4
    }
  },
  {
    "name": "EugeneTLT",
    "stats": {
      "spos": 33.4,
      "alle": 37.5,
      "expr": 55.5,
      "pers": 79.3,
      "horn": 8.4,
      "fame": 20.8,
      "shwr": 66.8,
      "sani": 45.8,
      "rela": 70.8,
      "fedp": 37.6,
      "actn": 66.8,
      "purp": 58.4,
      "perc": 71.0,
      "cmdy": 45.8
    }
  },
  {
    "name": "Froggers",
    "stats": {
      "spos": 41.6,
      "alle": 50.0,
      "expr": 61.2,
      "pers": 60.8,
      "horn": 35.0,
      "fame": 77.4,
      "shwr": 65.3,
      "sani": 44.5,
      "rela": 88.2,
      "fedp": 60.7,
      "actn": 43.7,
      "purp": 45.5,
      "perc": 75.1,
      "cmdy": 81.6
    }
  },
  {
    "name": "Beeper",
    "stats": {
      "spos": 37.5,
      "alle": 79.3,
      "expr": 61.2,
      "pers": 79.3,
      "horn": 41.6,
      "fame": 45.8,
      "shwr": 37.4,
      "sani": 75.1,
      "rela": 66.8,
      "fedp": 75.0,
      "actn": 70.1,
      "purp": 83.4,
      "perc": 54.1,
      "cmdy": 58.4
    }
  },
  {
    "name": "wasp_",
    "stats": {
      "spos": 58.4,
      "alle": 33.4,
      "expr": 89.0,
      "pers": 50.0,
      "horn": 70.8,
      "fame": 79.3,
      "shwr": 83.4,
      "sani": 54.3,
      "rela": 54.3,
      "fedp": 25.0,
      "actn": 66.7,
      "purp": 54.1,
      "perc": 54.1,
      "cmdy": 45.9
    }
  },
  {
    "name": "Vizdun",
    "stats": {
      "spos": 66.7,
      "alle": 78.4,
      "expr": 62.5,
      "pers": 32.2,
      "horn": 88.3,
      "fame": 68.2,
      "shwr": 19.2,
      "sani": 23.6,
      "rela": 8.3,
      "fedp": 46.4,
      "actn": 17.9,
      "purp": 36.3,
      "perc": 35.0,
      "cmdy": 77.8
    }
  },
  {
    "name": "Librlec ",
    "stats": {
      "spos": 23.2,
      "alle": 31.6,
      "expr": 23.5,
      "pers": 81.0,
      "horn": 61.7,
      "fame": 66.8,
      "shwr": 50.0,
      "sani": 62.5,
      "rela": 41.7,
      "fedp": 5.9,
      "actn": 79.6,
      "purp": 39.4,
      "perc": 41.8,
      "cmdy": 25.8
    }
  },
  {
    "name": "Chara",
    "stats": {
      "spos": 86.7,
      "alle": 12.7,
      "expr": 86.2,
      "pers": 83.6,
      "horn": 46.3,
      "fame": 84.8,
      "shwr": 53.8,
      "sani": 55.9,
      "rela": 67.1,
      "fedp": 12.2,
      "actn": 82.7,
      "purp": 88.0,
      "perc": 65.6,
      "cmdy": 50.1
    }
  }
];

userlink = "U2FsdGVkX1/BSiD5beXHcgi3TaXQI7FhqaEHsM/388w6QOHg7HhMEIbLPqvTqFE3RXsPqtjLf+dXdVI0YeSdvO32dGIAcWfGteS4C/g/60CFT6Mmjj1RoNCEbV5HcIY1xIco5A0B1fcSD8Z1/ZsqwEkllTA85izJk6d+Vd+baOC6nfZl8cFEFXO3X7J56Rgg";
