// Generated by CoffeeScript 2.5.1
var userlink, users;

users = [
  {
    "name": "No matches yet :P",
    "stats": {
      "spos": 0.0,
      "alle": 0.0,
      "expr": 0.0,
      "pers": 0.0,
      "horn": 0.0,
      "fame": 0.0,
      "shwr": 0.0,
      "sani": 0.0,
      "rela": 0.0,
      "fedp": 0.0,
      "actn": 0.0,
      "purp": 0.0,
      "perc": 0.0,
      "cmdy": 0.0
    }
  },
  {
    "name": "No matches yet :P",
    "stats": {
      "spos": 100.0,
      "alle": 100.0,
      "expr": 100.0,
      "pers": 100.0,
      "horn": 100.0,
      "fame": 100.0,
      "shwr": 100.0,
      "sani": 100.0,
      "rela": 100.0,
      "fedp": 100.0,
      "actn": 100.0,
      "purp": 100.0,
      "perc": 100.0,
      "cmdy": 100.0
    }
  }
];

userlink = "U2FsdGVkX1/BSiD5beXHcgi3TaXQI7FhqaEHsM/388w6QOHg7HhMEIbLPqvTqFE3RXsPqtjLf+dXdVI0YeSdvO32dGIAcWfGteS4C/g/60CFT6Mmjj1RoNCEbV5HcIY1xIco5A0B1fcSD8Z1/ZsqwEkllTA85izJk6d+Vd+baOC6nfZl8cFEFXO3X7J56Rgg";
